# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.xci
# IP: The module: 'refreshrate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'refreshrate'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.xci
# IP: The module: 'refreshrate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'refreshrate'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
