# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.cache/wt} [current_project]
set_property parent.project_path {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet {{w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.xci}}
set_property is_locked true [get_files {{w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.xci}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1} -new_name refreshrate -ip [get_ips refreshrate]]

if { $cached_ip eq {} } {

synth_design -top refreshrate -part xc7a100tcsg324-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix refreshrate_ refreshrate.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ refreshrate_stub.v
 lappend ipCachedFiles refreshrate_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ refreshrate_stub.vhdl
 lappend ipCachedFiles refreshrate_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ refreshrate_sim_netlist.v
 lappend ipCachedFiles refreshrate_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ refreshrate_sim_netlist.vhdl
 lappend ipCachedFiles refreshrate_sim_netlist.vhdl

 config_ip_cache -add -dcp refreshrate.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips refreshrate]
}

rename_ref -prefix_all refreshrate_

write_checkpoint -force -noxdef refreshrate.dcp

catch { report_utilization -file refreshrate_utilization_synth.rpt -pb refreshrate_utilization_synth.pb }

if { [catch {
  file copy -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate.dcp} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate.dcp} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate_stub.v} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate_stub.vhdl} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate_sim_netlist.v} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.runs/refreshrate_synth_1/refreshrate_sim_netlist.vhdl} {w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.ip_user_files/ip/refreshrate}]} {
  catch { 
    file copy -force {{w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.v}} {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.ip_user_files/ip/refreshrate}
  }
}

if {[file isdir {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.ip_user_files/ip/refreshrate}]} {
  catch { 
    file copy -force {{w:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.srcs/sources_1/ip/refreshrate/refreshrate_stub.vhdl}} {W:/Desktop/ELEC 3500 LABS/lab9_3_1/lab9_3_1.ip_user_files/ip/refreshrate}
  }
}
