# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/Desktop/ELEC 3500 LABS/stopwatch_project/stopwatch_project.srcs/sources_1/ip/rate10thousandth_1/rate10thousandth.xci
# IP: The module: 'rate10thousandth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/Desktop/ELEC 3500 LABS/stopwatch_project/stopwatch_project.srcs/sources_1/ip/rate10thousandth_1/rate10thousandth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rate10thousandth'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: w:/Desktop/ELEC 3500 LABS/stopwatch_project/stopwatch_project.srcs/sources_1/ip/rate10thousandth_1/rate10thousandth.xci
# IP: The module: 'rate10thousandth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/Desktop/ELEC 3500 LABS/stopwatch_project/stopwatch_project.srcs/sources_1/ip/rate10thousandth_1/rate10thousandth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rate10thousandth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
